

;
; �������������������������������������������������������������������������ͻ
; �	This file is generated by The Interactive Disassembler (IDA)	    �
; �	Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>	    �
; �			 Licensed to: Freeware version			    �
; �������������������������������������������������������������������������ͼ
;
; Input	MD5   :	8FC662BF4D48A72CE1242CA569BBCA35

; File Name   :	TURBO.COM
; Format      :	MS-DOS COM-file
; Base Address:	0h Range: 100h-68E0h Loaded length: 67E0h


; ���������������������������������������������������������������������������

; Segment type:	Pure code
		org 100h


; ��������������� S U B	R O U T	I N E ���������������������������������������


; FUNCTION CHUNK AT 0ECF SIZE 000000D3 BYTES
; FUNCTION CHUNK AT 0FA3 SIZE 00000028 BYTES
; FUNCTION CHUNK AT 0FCC SIZE 00000015 BYTES
; FUNCTION CHUNK AT 0FE2 SIZE 00000022 BYTES
; FUNCTION CHUNK AT 1005 SIZE 00000112 BYTES
; FUNCTION CHUNK AT 1118 SIZE 0000006B BYTES
; FUNCTION CHUNK AT 1184 SIZE 0000031C BYTES
; FUNCTION CHUNK AT 14A1 SIZE 00000023 BYTES
; FUNCTION CHUNK AT 14C5 SIZE 000000E6 BYTES
; FUNCTION CHUNK AT 17B3 SIZE 00000007 BYTES

		push	cs
		pop	ds
		jmp	loc_CAD  ; jump to start of code at 0xCAD
; ���������������������������������������������������������������������������
		db  66h	; f
		db    0
str_107	db  50h	; P
word_108	dw 7443h		; DATA XREF: sub_15AB+Dr
word_10A	dw 7275h		; DATA XREF: sub_15AB+10r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  65h	; e
		db  20h
		db  53h	; S
		db  79h	; y
		db  73h	; s
		db  74h	; t
		db  65h	; e
		db  6Dh	; m
		db  20h
		db  56h	; V
		db  65h	; e
		db  72h	; r
		db  73h	; s
		db  69h	; i
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  31h	; 1
		db  2Eh	; .
		db  32h	; 2
		db  36h	; 6
		db  20h
		db  20h
		db  24h	; $
str_12a		db  0Ah
		db  0Dh
		db  28h	; (
		db  43h	; C
		db  29h	; )
		db  20h
		db  43h	; C
		db  6Fh	; o
		db  70h	; p
		db  79h	; y
		db  72h	; r
		db  69h	; i
		db  67h	; g
		db  68h	; h
		db  74h	; t
		db  20h
		db  31h	; 1
		db  39h	; 9
		db  38h	; 8
		db  36h	; 6
		db  20h
		db  4Dh	; M
		db  6Fh	; o
		db  72h	; r
		db  65h	; e
		db  20h
		db  43h	; C
		db  6Fh	; o
		db  6Dh	; m
		db  70h	; p
		db  75h	; u
		db  74h	; t
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  2Eh	; .
		db  20h
		db  41h	; A
		db  6Ch	; l
		db  6Ch	; l
		db  20h
		db  52h	; R
		db  69h	; i
		db  67h	; g
		db  68h	; h
		db  74h	; t
		db  73h	; s
		db  20h
		db  52h	; R
		db  65h	; e
		db  73h	; s
		db  65h	; e
		db  72h	; r
		db  76h	; v
		db  65h	; e
		db  64h	; d
		db  2Eh	; .
		db  0Ah
		db  0Dh
		db  24h	; $
		db  5Ah	; Z
		db 0A5h	; �
		db  31h	; 1
		db  32h	; 2
		db  36h	; 6
byte_16B	db 7			; IRQ   DATA XREF: start:loc_D71w start+E6Dr ...
byte_16C	db 0			; DATA XREF: start+D10w start:loc_EF8r
byte_16D	db 0			; DATA XREF: start+D1Dw sub_3DA9+Dr
byte_16E	db 1			; DATA XREF: start+D37w start+D48w ...
byte_16F	db 1			; DATA XREF: start+D59w start+EEFr ...
byte_170	db 1			; DATA XREF: start+CE9w start+D2Aw ...
		db    0
byte_172	db 0			; DATA XREF: start+C23w start+ED2r ...
		db    0
		db    0
byte_175	db 0			; DATA XREF: start:loc_FA9r
					; start:loc_102Er
		db    0
byte_177	db 0			; DATA XREF: start+D54w start:loc_FE8r ...
word_178	dw 700h			; DATA XREF: start+FC7r start+FCFr ...
		db    5
		db    7
		db    7
		db    7
		db    6
		db    7
word_180	dw 300h			; DATA XREF: start+E4Cr start+E58r ...
word_182	dw 0E000h		; DATA XREF: start:loc_DB1w start+DE6r ...
		db    1
byte_185	db 0			; DATA XREF: start+D03w start:loc_F1Er ...
word_186	dw 280h			; DATA XREF: start:loc_DD8w start+E81r ...
		db    0
byte_189	db 0			; DATA XREF: start+C8Cw
					; start:loc_126Fr
byte_18A	db 0			; DATA XREF: start+D65w start:loc_FB6r ...
byte_18B	db 0			; DATA XREF: start+D76w start+1142w ...
byte_18C	db 0			; DATA XREF: start+145Fr sub_15AB+4w
byte_18D	db 0			; DATA XREF: start+1443r sub_15AB+2Bw
word_18E	dw 0			; DATA XREF: start+1447r sub_15AB+24w
word_190	dw 0			; DATA XREF: start+144Ar sub_15AB+27w
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db  73h	; s
		db  74h	; t
		db  61h	; a
		db  63h	; c
		db  6Bh	; k
		db  20h
		db  62h	; b
		db  61h	; a
		db  73h	; s
		db  65h	; e
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db  73h	; s
		db    0
str_3A3h		db  0Ah
		db  0Dh
		db  43h	; C
		db  61h	; a
		db  6Eh	; n
		db  6Eh	; n
		db  6Fh	; o
		db  74h	; t
		db  20h
		db  61h	; a
		db  63h	; c
		db  63h	; c
		db  65h	; e
		db  73h	; s
		db  73h	; s
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  65h	; e
		db  20h
		db  43h	; C
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  2Eh	; .
		db  20h
		db  50h	; P
		db  6Ch	; l
		db  65h	; e
		db  61h	; a
		db  73h	; s
		db  65h	; e
		db  20h
		db  63h	; c
		db  68h	; h
		db  65h	; e
		db  63h	; c
		db  6Bh	; k
		db  20h
		db  61h	; a
		db  6Ch	; l
		db  6Ch	; l
		db  0Ah
		db  0Dh
		db  62h	; b
		db  6Fh	; o
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  20h
		db  6Ah	; j
		db  75h	; u
		db  6Dh	; m
		db  70h	; p
		db  65h	; e
		db  72h	; r
		db  73h	; s
		db  20h
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  74h	; t
		db  72h	; r
		db  79h	; y
		db  20h
		db  61h	; a
		db  67h	; g
		db  61h	; a
		db  69h	; i
		db  6Eh	; n
		db  2Eh	; .
		db  0Ah
str_3F9h		db  0Ah
		db  0Dh
		db  24h	; $
str_3fc		db  45h	; E
		db  72h	; r
		db  72h	; r
		db  6Fh	; o
		db  72h	; r
		db  20h
		db  69h	; i
		db  6Eh	; n
		db  20h
		db  63h	; c
		db  6Fh	; o
		db  6Dh	; m
		db  6Dh	; m
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  61h	; a
		db  72h	; r
		db  67h	; g
byte_410	db 75h			; DATA XREF: start+1454w start+1459w ...
		db  6Dh	; m
		db  65h	; e
		db  6Eh	; n
		db  74h	; t
		db  20h
		db  73h	; s
word_417	dw 7274h		; DATA XREF: start+1294r start+1482w
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  3Ah	; :
		db  20h
		db  24h	; $
str_41f		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  24h	; $
str_442h		db  0Ah
		db  0Dh
		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  65h	; e
		db  20h
		db  43h	; C
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  20h
		db  6Eh	; n
		db  6Fh	; o
		db  74h	; t
		db  20h
		db  72h	; r
		db  65h	; e
		db  73h	; s
		db  70h	; p
		db  6Fh	; o
		db  6Eh	; n
		db  64h	; d
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  2Eh	; .
byte_465	db 20h			; DATA XREF: start+12DBr start+1305r
		db  50h	; P
		db  6Ch	; l
		db  65h	; e
		db  61h	; a
		db  73h	; s
		db  65h	; e
		db  20h
		db  63h	; c
		db  68h	; h
		db  65h	; e
		db  63h	; c
		db  6Bh	; k
		db  20h
		db  61h	; a
		db  6Ch	; l
		db  6Ch	; l
		db  20h
		db  62h	; b
		db  6Fh	; o
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  0Ah
		db  0Dh
		db  6Ah	; j
		db  75h	; u
		db  6Dh	; m
		db  70h	; p
		db  65h	; e
		db  72h	; r
		db  73h	; s
		db  20h
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  74h	; t
		db  72h	; r
		db  79h	; y
		db  20h
		db  61h	; a
		db  67h	; g
		db  61h	; a
		db  69h	; i
		db  6Eh	; n
		db  2Eh	; .
		db  0Ah
		db  0Ah
		db  0Dh
		db  24h	; $
str_498h		db  0Ah
		db  0Dh
		db  53h	; S
		db  54h	; T
		db  41h	; A
		db  52h	; R
		db  54h	; T
		db  55h	; U
		db  50h	; P
		db  20h
		db  45h	; E
		db  52h	; R
		db  52h	; R
		db  4Fh	; O
		db  52h	; R
		db  20h
		db  2Dh	; -
		db  20h
		db  63h	; c
		db  61h	; a
		db  6Eh	; n
		db  6Eh	; n
		db  6Fh	; o
		db  74h	; t
		db  20h
		db  61h	; a
		db  63h	; c
		db  63h	; c
		db  65h	; e
		db  73h	; s
		db  73h	; s
		db  20h
		db  64h	; d
		db  61h	; a
		db  75h	; u
		db  67h	; g
		db  68h	; h
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  63h	; c
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  20h
		db  6Dh	; m
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  20h
		db  61h	; a
		db  73h	; s
		db  20h
		db  63h	; c
		db  6Fh	; o
		db  6Eh	; n
		db  66h	; f
		db  69h	; i
		db  67h	; g
		db  75h	; u
		db  72h	; r
		db  65h	; e
		db  64h	; d
		db  2Eh	; .
		db  0Ah
		db  0Ah
		db  0Dh
		db  54h	; T
		db  68h	; h
		db  69h	; i
		db  73h	; s
		db  20h
		db  54h	; T
		db  55h	; U
		db  52h	; R
		db  42h	; B
		db  4Fh	; O
		db  2Eh	; .
		db  43h	; C
		db  4Fh	; O
		db  4Dh	; M
		db  20h
		db  68h	; h
		db  61h	; a
		db  73h	; s
		db  20h
		db  62h	; b
		db  65h	; e
		db  65h	; e
		db  6Eh	; n
		db  20h
		db  63h	; c
		db  6Fh	; o
		db  6Eh	; n
		db  66h	; f
		db  69h	; i
		db  67h	; g
		db  75h	; u
		db  72h	; r
		db  65h	; e
		db  64h	; d
		db  20h
		db  66h	; f
		db  6Fh	; o
		db  72h	; r
		db  20h
		db  61h	; a
		db  20h
		db  6Dh	; m
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  20h
		db  64h	; d
		db  61h	; a
		db  75h	; u
		db  67h	; g
		db  68h	; h
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  63h	; c
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  20h
		db  61h	; a
		db  63h	; c
		db  74h	; t
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  0Ah
		db  0Dh
		db  61h	; a
		db  73h	; s
		db  20h
		db  41h	; A
		db  54h	; T
		db  2Dh	; -
		db  73h	; s
		db  74h	; t
		db  79h	; y
		db  6Ch	; l
		db  65h	; e
		db  20h
		db  65h	; e
		db  78h	; x
		db  70h	; p
		db  61h	; a
		db  6Eh	; n
		db  73h	; s
		db  69h	; i
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  6Dh	; m
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  2Ch	; ,
		db  20h
		db  62h	; b
		db  75h	; u
		db  74h	; t
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  64h	; d
		db  61h	; a
		db  75h	; u
		db  67h	; g
		db  68h	; h
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  63h	; c
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  20h
		db  63h	; c
		db  61h	; a
		db  6Eh	; n
		db  6Eh	; n
		db  6Fh	; o
		db  74h	; t
		db  20h
		db  62h	; b
		db  65h	; e
		db  20h
		db  61h	; a
		db  63h	; c
		db  63h	; c
		db  65h	; e
		db  73h	; s
		db  73h	; s
		db  65h	; e
		db  64h	; d
		db  2Eh	; .
		db  0Ah
		db  0Dh
		db  43h	; C
		db  68h	; h
		db  65h	; e
		db  63h	; c
		db  6Bh	; k
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  6Dh	; m
		db  61h	; a
		db  69h	; i
		db  6Eh	; n
		db  20h
		db  62h	; b
		db  6Fh	; o
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  27h	; '
		db  73h	; s
		db  20h
		db  31h	; 1
		db  4Dh	; M
		db  20h
		db  2Fh	; /
		db  20h
		db  32h	; 2
		db  4Dh	; M
		db  20h
		db  6Ah	; j
		db  75h	; u
		db  6Dh	; m
		db  70h	; p
		db  65h	; e
		db  72h	; r
		db  20h
		db  28h	; (
		db  73h	; s
		db  68h	; h
		db  6Fh	; o
		db  75h	; u
		db  6Ch	; l
		db  64h	; d
		db  20h
		db  62h	; b
		db  65h	; e
		db  20h
		db  32h	; 2
		db  4Dh	; M
		db  29h	; )
		db  2Ch	; ,
		db  20h
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  72h	; r
		db  65h	; e
		db  2Dh	; -
		db  69h	; i
		db  6Eh	; n
		db  73h	; s
		db  74h	; t
		db  61h	; a
		db  6Ch	; l
		db  6Ch	; l
		db  2Eh	; .
		db  0Ah
		db  0Dh
		db  0Ah
		db  24h	; $
		db  43h	; C
		db  61h	; a
		db  6Eh	; n
		db  6Eh	; n
		db  6Fh	; o
		db  74h	; t
		db  20h
		db  6Fh	; o
		db  70h	; p
		db  65h	; e
		db  6Eh	; n
		db  2Fh	; /
		db  72h	; r
		db  65h	; e
		db  61h	; a
		db  64h	; d
		db  20h
		db  66h	; f
		db  69h	; i
		db  6Ch	; l
		db  65h	; e
		db  20h
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  42h	; B
		db  49h	; I
		db  4Fh	; O
		db  53h	; S
		db  2Eh	; .
		db  42h	; B
		db  49h	; I
		db  4Eh	; N
		db  0Ah
		db  0Dh
		db  24h	; $
str_5D7h		db  49h	; I
		db  6Eh	; n
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  6Eh	; n
		db  61h	; a
		db  6Ch	; l
		db  20h
		db  66h	; f
		db  6Fh	; o
		db  72h	; r
		db  6Dh	; m
		db  61h	; a
		db  74h	; t
		db  20h
		db  65h	; e
		db  72h	; r
		db  72h	; r
		db  6Fh	; o
		db  72h	; r
		db  20h
		db  2Dh	; -
		db  20h
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  20h
		db  42h	; B
		db  69h	; i
		db  6Fh	; o
		db  73h	; s
		db  20h
		db  63h	; c
		db  6Fh	; o
		db  64h	; d
		db  65h	; e
		db  20h
		db  6Dh	; m
		db  69h	; i
		db  73h	; s
		db  73h	; s
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  0Ah
		db  0Dh
		db  24h	; $
str_607h		db  45h	; E
		db  4Dh	; M
		db  4Dh	; M
		db  58h	; X
		db  58h	; X
		db  58h	; X
		db  58h	; X
		db  30h	; 0
		db    0
str_610h		db  0Ah
		db  0Dh
		db  53h	; S
		db  54h	; T
		db  41h	; A
		db  52h	; R
		db  54h	; T
		db  55h	; U
		db  50h	; P
		db  20h
		db  45h	; E
		db  52h	; R
		db  52h	; R
		db  4Fh	; O
		db  52h	; R
		db  20h
		db  2Dh	; -
		db  20h
		db  45h	; E
		db  78h	; x
		db  74h	; t
		db  65h	; e
		db  6Eh	; n
		db  64h	; d
		db  65h	; e
		db  64h	; d
		db  20h
		db  4Dh	; M
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  20h
		db  28h	; (
		db  45h	; E
		db  4Dh	; M
		db  4Dh	; M
		db  29h	; )
		db  20h
		db  64h	; d
		db  72h	; r
		db  69h	; i
		db  76h	; v
		db  65h	; e
		db  72h	; r
		db  20h
		db  69h	; i
		db  6Eh	; n
		db  73h	; s
		db  74h	; t
		db  61h	; a
		db  6Ch	; l
		db  6Ch	; l
		db  65h	; e
		db  64h	; d
		db  20h
		db  61h	; a
		db  74h	; t
		db  20h
		db  73h	; s
		db  61h	; a
		db  6Dh	; m
		db  65h	; e
		db  20h
		db  6Dh	; m
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  0Ah
		db  0Dh
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  73h	; s
		db  65h	; e
		db  67h	; g
		db  6Dh	; m
		db  65h	; e
		db  6Eh	; n
		db  74h	; t
		db  20h
		db  61h	; a
		db  64h	; d
		db  64h	; d
		db  72h	; r
		db  65h	; e
		db  73h	; s
		db  73h	; s
		db  20h
		db  61h	; a
		db  73h	; s
		db  20h
		db  54h	; T
		db  55h	; U
		db  52h	; R
		db  42h	; B
		db  4Fh	; O
		db  2Eh	; .
		db  43h	; C
		db  4Fh	; O
		db  4Dh	; M
		db  2Eh	; .
		db  0Ah
		db  0Ah
		db  0Dh
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  50h	; P
		db  6Ch	; l
		db  65h	; e
		db  61h	; a
		db  73h	; s
		db  65h	; e
		db  20h
		db  52h	; R
		db  45h	; E
		db  2Dh	; -
		db  49h	; I
		db  4Eh	; N
		db  53h	; S
		db  54h	; T
		db  41h	; A
		db  4Ch	; L
		db  4Ch	; L
		db  20h
		db  79h	; y
		db  6Fh	; o
		db  75h	; u
		db  72h	; r
		db  20h
		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  65h	; e
		db  20h
		db  73h	; s
		db  79h	; y
		db  73h	; s
		db  74h	; t
		db  65h	; e
		db  6Dh	; m
		db  20h
		db  73h	; s
		db  6Fh	; o
		db  66h	; f
		db  74h	; t
		db  77h	; w
		db  61h	; a
		db  72h	; r
		db  65h	; e
		db  2Eh	; .
		db  0Ah
		db  0Dh
		db  0Ah
		db  0Dh
		db  24h	; $
str_6D2		db  41h	; A
		db  6Ch	; l
		db  72h	; r
		db  65h	; e
		db  61h	; a
		db  64h	; d
		db  79h	; y
		db  20h
		db  65h	; e
		db  78h	; x
		db  65h	; e
		db  63h	; c
		db  75h	; u
		db  74h	; t
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  20h
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  21h	; !
		db  0Ah
		db  0Dh
		db  24h	; $
str_6FAh		db  4Eh	; N
		db  6Fh	; o
		db  77h	; w
		db  20h
		db  65h	; e
		db  78h	; x
		db  65h	; e
		db  63h	; c
		db  75h	; u
		db  74h	; t
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  20h
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  68h	; h
		db  6Fh	; o
		db  73h	; s
		db  74h	; t
		db  20h
		db  6Dh	; m
		db  61h	; a
		db  63h	; c
		db  68h	; h
		db  69h	; i
		db  6Eh	; n
		db  65h	; e
		db  2Eh	; .
		db  0Ah
		db  0Dh
		db  24h	; $
str_71b		db  54h	; T
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  20h
		db  41h	; A
		db  6Ch	; l
		db  72h	; r
		db  65h	; e
		db  61h	; a
		db  64h	; d
		db  79h	; y
		db  20h
		db  4Ch	; L
		db  6Fh	; o
		db  61h	; a
		db  64h	; d
		db  65h	; e
		db  64h	; d
		db  2Eh	; .
		db  20h
		db  28h	; (
		db  2Fh	; /
		db  21h	; !
		db  20h
		db  6Fh	; o
		db  70h	; p
		db  74h	; t
		db  69h	; i
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  75h	; u
		db  73h	; s
		db  65h	; e
		db  64h	; d
		db  2Eh	; .
		db  20h
		db  55h	; U
		db  73h	; s
		db  65h	; e
		db  20h
		db  41h	; A
		db  6Ch	; l
		db  74h	; t
		db  2Dh	; -
		db  67h	; g
		db  72h	; r
		db  65h	; e
		db  79h	; y
		db  2Bh	; +
		db  20h
		db  74h	; t
		db  6Fh	; o
		db  20h
		db  73h	; s
		db  77h	; w
		db  61h	; a
		db  70h	; p
		db  29h	; )
		db  0Ah
		db  0Dh
		db  24h	; $
		db    7
		db  50h	; P
		db  43h	; C
		db  4Dh	; M
		db  41h	; A
		db  49h	; I
		db  4Eh	; N
		db  3Ah	; :
		db  20h
		db  49h	; I
		db  6Eh	; n
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  66h	; f
		db  61h	; a
		db  63h	; c
		db  65h	; e
		db  20h
		db  45h	; E
		db  72h	; r
		db  72h	; r
		db  6Fh	; o
		db  72h	; r
		db  20h
		db  2Dh	; -
		db  20h
		db  55h	; U
		db  6Eh	; n
		db  65h	; e
		db  78h	; x
		db  70h	; p
		db  65h	; e
		db  63h	; c
		db  74h	; t
		db  65h	; e
		db  64h	; d
		db  20h
		db  63h	; c
		db  6Fh	; o
		db  6Dh	; m
		db  6Dh	; m
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  69h	; i
		db  6Eh	; n
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  72h	; r
		db  75h	; u
		db  70h	; p
		db  74h	; t
		db  0Ah
		db  0Dh
		db  24h	; $
		db    7
		db  50h	; P
		db  43h	; C
		db  4Dh	; M
		db  41h	; A
		db  49h	; I
		db  4Eh	; N
		db  3Ah	; :
		db  20h
		db  49h	; I
		db  6Eh	; n
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  66h	; f
		db  61h	; a
		db  63h	; c
		db  65h	; e
		db  20h
		db  45h	; E
		db  72h	; r
		db  72h	; r
		db  6Fh	; o
		db  72h	; r
		db  20h
		db  2Dh	; -
		db  20h
		db  53h	; S
		db  70h	; p
		db  75h	; u
		db  72h	; r
		db  69h	; i
		db  6Fh	; o
		db  75h	; u
		db  73h	; s
		db  20h
		db  69h	; i
		db  6Eh	; n
		db  74h	; t
		db  20h
		db  37h	; 7
		db  20h
		db  6Fh	; o
		db  63h	; c
		db  63h	; c
		db  75h	; u
		db  72h	; r
		db  72h	; r
		db  65h	; e
		db  64h	; d
		db  0Ah
		db  0Dh
		db  24h	; $
str_7CAh		db  53h	; S
		db  54h	; T
		db  41h	; A
		db  52h	; R
		db  54h	; T
		db  55h	; U
		db  50h	; P
		db  20h
		db  45h	; E
		db  52h	; R
		db  52h	; R
		db  4Fh	; O
		db  52h	; R
		db  20h
		db  2Dh	; -
		db  20h
		db  4Eh	; N
		db  6Fh	; o
		db  74h	; t
		db  20h
		db  65h	; e
		db  6Eh	; n
		db  6Fh	; o
		db  75h	; u
		db  67h	; g
		db  68h	; h
		db  20h
		db  6Dh	; m
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  20h
		db  74h	; t
		db  6Fh	; o
		db  20h
		db  6Ch	; l
		db  6Fh	; o
		db  61h	; a
		db  64h	; d
		db  20h
		db  70h	; p
		db  72h	; r
		db  6Fh	; o
		db  67h	; g
		db  72h	; r
		db  61h	; a
		db  6Dh	; m
		db  2Eh	; .
		db  0Ah
		db  0Dh
		db  24h	; $
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  42h	; B
		db  49h	; I
		db  4Fh	; O
		db  53h	; S
		db  2Eh	; .
		db  42h	; B
		db  49h	; I
		db  4Eh	; N
		db    0	
str_80Bh	db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
str_816h		db  54h	; T
		db  55h	; U
		db  52h	; R
		db  42h	; B
		db  4Fh	; O
		db  20h
		db  43h	; C
		db  6Fh	; o
		db  6Dh	; m
		db  6Dh	; m
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  53h	; S
		db  6Fh	; o
		db  66h	; f
		db  74h	; t
		db  77h	; w
		db  61h	; a
		db  72h	; r
		db  65h	; e
		db  20h
		db  43h	; C
		db  6Fh	; o
		db  6Eh	; n
		db  66h	; f
		db  69h	; i
		db  67h	; g
		db  75h	; u
		db  72h	; r
		db  61h	; a
		db  74h	; t
		db  69h	; i
		db  6Fh	; o
		db  6Eh	; n
		db  3Ah	; :
		db  0Ah
		db  0Dh
		db  24h	; $
str_83Eh		db  20h
		db  20h
		db  20h
		db  44h	; D
		db  75h	; u
		db  61h	; a
		db  6Ch	; l
		db  20h
		db  50h	; P
		db  6Fh	; o
		db  72h	; r
		db  74h	; t
		db  20h
		db  4Dh	; M
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  20h
		db  41h	; A
		db  64h	; d
		db  64h	; d
		db  72h	; r
		db  65h	; e
		db  73h	; s
		db  73h	; s
		db  20h
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  20h
		db  24h	; $
str_860h		db  3Ah	; :
		db  30h	; 0
		db  20h
		db  28h	; (
		db  68h	; h
		db  65h	; e
		db  78h	; x
		db  29h	; )
		db  0Ah
		db  0Dh
		db  24h	; $
str_86Bh		db  20h
		db  20h
		db  20h
		db  49h	; I
		db  2Fh	; /
		db  4Fh	; O
		db  20h
		db  50h	; P
		db  6Fh	; o
		db  72h	; r
		db  74h	; t
		db  20h
		db  41h	; A
		db  64h	; d
		db  64h	; d
		db  72h	; r
		db  65h	; e
		db  73h	; s
		db  73h	; s
		db  20h
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
byte_888	db 2Eh			; DATA XREF: start+1119r
		db  2Eh	; .
		db  2Eh	; .
		db  20h
		db  24h	; $
str_88Dh		db  20h
		db  74h	; t
		db  6Fh	; o
		db  20h
		db  24h	; $
str_892h		db  20h
		db  20h
		db  20h
		db  49h	; I
		db  6Eh	; n
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  72h	; r
		db  75h	; u
		db  70h	; p
		db  74h	; t
		db  20h
		db  52h	; R
		db  65h	; e
		db  71h	; q
		db  75h	; u
		db  65h	; e
		db  73h	; s
		db  74h	; t
		db  20h
		db  4Ch	; L
		db  69h	; i
		db  6Eh	; n
		db  65h	; e
		db  20h
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  20h
		db  24h	; $
str_8B4h		db  20h
		db  20h
		db  20h
		db  46h	; F
		db  61h	; a
		db  73h	; s
		db  74h	; t
		db  20h
		db  63h	; c
		db  6Fh	; o
		db  6Ch	; l
		db  6Fh	; o
		db  72h	; r
		db  2Fh	; /
		db  67h	; g
		db  72h	; r
		db  61h	; a
		db  70h	; p
		db  68h	; h
		db  69h	; i
		db  63h	; c
		db  73h	; s
		db  20h
		db  75h	; u
		db  70h	; p
		db  64h	; d
		db  61h	; a
		db  74h	; t
		db  65h	; e
		db  20h
		db  2Eh	; .
		db  2Eh	; .
		db  20h
		db  24h	; $
str_8D6h		db  20h
		db  20h
		db  20h
		db  48h	; H
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  20h
		db  44h	; D
		db  69h	; i
		db  73h	; s
		db  6Bh	; k
		db  20h
		db  62h	; b
		db  6Fh	; o
		db  6Fh	; o
		db  74h	; t
		db  20h
		db  66h	; f
		db  6Ch	; l
		db  61h	; a
		db  67h	; g
		db  20h
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  20h
		db  24h	; $
str_8F8h		db  4Fh	; O
		db  4Eh	; N
		db  0Ah
		db  0Dh
		db  24h	; $
str_8FDh		db  4Fh	; O
		db  46h	; F
		db  46h	; F
		db  0Ah
		db  0Dh
		db  24h	; $
str_903h		db  20h
		db  20h
		db  20h
		db  44h	; D
		db  4Fh	; O
		db  53h	; S
		db  20h
		db  4Dh	; M
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  20h
		db  53h	; S
		db  69h	; i
		db  7Ah	; z
		db  65h	; e
		db  20h
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  20h
		db  24h	; $
str_925h		db  20h
		db  20h
		db  20h
		db  48h	; H
		db  65h	; e
		db  72h	; r
		db  63h	; c
		db  75h	; u
		db  6Ch	; l
		db  65h	; e
		db  73h	; s
		db  20h
		db  4Dh	; M
		db  6Fh	; o
		db  6Eh	; n
		db  6Fh	; o
		db  20h
		db  47h	; G
		db  72h	; r
		db  61h	; a
		db  70h	; p
		db  68h	; h
		db  69h	; i
		db  63h	; c
		db  73h	; s
		db  20h
		db  41h	; A
		db  64h	; d
		db  61h	; a
		db  70h	; p
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  20h
		db  49h	; I
		db  6Eh	; n
		db  73h	; s
		db  74h	; t
		db  61h	; a
		db  6Ch	; l
		db  6Ch	; l
		db  65h	; e
		db  64h	; d
		db  24h	; $
str_951h		db  20h
		db  20h
		db  20h
		db  4Fh	; O
		db  72h	; r
		db  63h	; c
		db  68h	; h
		db  69h	; i
		db  64h	; d
		db  20h
		db  44h	; D
		db  42h	; B
		db  55h	; U
		db  53h	; S
		db  20h
		db  45h	; E
		db  47h	; G
		db  41h	; A
		db  20h
		db  43h	; C
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  20h
		db  49h	; I
		db  6Eh	; n
		db  73h	; s
		db  74h	; t
		db  61h	; a
		db  6Ch	; l
		db  6Ch	; l
		db  65h	; e
		db  64h	; d
		db  24h	; $
str_973h		db  20h
		db  20h
		db  20h
		db  4Dh	; M
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  20h
		db  44h	; D
		db  61h	; a
		db  75h	; u
		db  67h	; g
		db  68h	; h
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  63h	; c
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  20h
		db  49h	; I
		db  6Eh	; n
		db  73h	; s
		db  74h	; t
		db  61h	; a
		db  6Ch	; l
		db  6Ch	; l
		db  65h	; e
		db  64h	; d
		db  20h
		db  61h	; a
		db  73h	; s
		db  20h
		db  41h	; A
		db  54h	; T
		db  20h
		db  6Dh	; m
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  24h	; $
str_9A1h		db  20h
		db  20h
		db  20h
		db  4Dh	; M
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  20h
		db  44h	; D
		db  61h	; a
		db  75h	; u
		db  67h	; g
		db  68h	; h
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  63h	; c
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  20h
		db  49h	; I
		db  6Eh	; n
		db  73h	; s
		db  74h	; t
		db  61h	; a
		db  6Ch	; l
		db  6Ch	; l
		db  65h	; e
		db  64h	; d
		db  20h
		db  61h	; a
		db  73h	; s
		db  20h
		db  45h	; E
		db  4Dh	; M
		db  53h	; S
		db  20h
		db  6Dh	; m
		db  65h	; e
		db  6Dh	; m
		db  6Fh	; o
		db  72h	; r
		db  79h	; y
		db  24h	; $
str_9D0h		db  48h	; H
		db  69h	; i
		db  74h	; t
		db  20h
		db  41h	; A
		db  6Eh	; n
		db  79h	; y
		db  20h
		db  4Bh	; K
		db  65h	; e
		db  79h	; y
		db  20h
		db  74h	; t
		db  6Fh	; o
		db  20h
		db  43h	; C
		db  6Fh	; o
		db  6Eh	; n
		db  74h	; t
		db  69h	; i
		db  6Eh	; n
		db  75h	; u
		db  65h	; e
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  24h	; $
str_9EBh		db  49h	; I
		db  6Eh	; n
		db  69h	; i
		db  74h	; t
		db  69h	; i
		db  61h	; a
		db  6Ch	; l
		db  69h	; i
		db  7Ah	; z
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  20h
		db  31h	; 1
		db  20h
		db  4Dh	; M
		db  65h	; e
		db  67h	; g
		db  20h
		db  44h	; D
		db  61h	; a
		db  75h	; u
		db  67h	; g
		db  68h	; h
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  43h	; C
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  24h	; $
str_0A0Eh		db  0Dh
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  0Dh
		db  24h	; $
str_0A33h		db  54h	; T
		db  68h	; h
		db  65h	; e
		db  20h
		db  2Fh	; /
		db  53h	; S
		db  20h
		db  6Fh	; o
		db  70h	; p
		db  74h	; t
		db  69h	; i
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  6Fh	; o
		db  66h	; f
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  20h
		db  63h	; c
		db  6Fh	; o
		db  6Dh	; m
		db  6Dh	; m
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  69h	; i
		db  73h	; s
		db  20h
		db  6Eh	; n
		db  6Fh	; o
		db  74h	; t
		db  20h
		db  63h	; c
		db  75h	; u
		db  72h	; r
		db  72h	; r
		db  65h	; e
		db  6Eh	; n
		db  74h	; t
		db  6Ch	; l
		db  79h	; y
		db  20h
		db  73h	; s
		db  75h	; u
		db  70h	; p
		db  70h	; p
		db  6Fh	; o
		db  72h	; r
		db  74h	; t
		db  65h	; e
		db  64h	; d
		db  2Eh	; .
		db  0Ah
		db  0Dh
		db  24h	; $
str_0A74h		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  43h	; C
		db  6Fh	; o
		db  70h	; p
		db  72h	; r
		db  6Fh	; o
		db  63h	; c
		db  65h	; e
		db  73h	; s
		db  73h	; s
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  20h
		db  56h	; V
		db  65h	; e
		db  72h	; r
		db  73h	; s
		db  69h	; i
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  6Fh	; o
		db  66h	; f
		db  20h
		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  65h	; e
		db  20h
		db  53h	; S
		db  79h	; y
		db  73h	; s
		db  74h	; t
		db  65h	; e
		db  6Dh	; m
		db  20h
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  59h	; Y
		db  4Fh	; O
		db  55h	; U
		db  20h
		db  4Dh	; M
		db  55h	; U
		db  53h	; S
		db  54h	; T
		db  20h
		db  52h	; R
		db  45h	; E
		db  41h	; A
		db  44h	; D
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  44h	; D
		db  49h	; I
		db  53h	; S
		db  4Bh	; K
		db  20h
		db  57h	; W
		db  61h	; a
		db  72h	; r
		db  6Eh	; n
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  20h
		db  69h	; i
		db  6Eh	; n
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  5Ch	
		db  41h	; A
		db  44h	; D
		db  56h	; V
		db  41h	; A
		db  4Eh	; N
		db  43h	; C
		db  45h	; E
		db  44h	; D
		db  5Ch	
		db  52h	; R
		db  45h	; E
		db  41h	; A
		db  44h	; D
		db  4Dh	; M
		db  45h	; E
		db  20h
		db  66h	; f
		db  69h	; i
		db  6Ch	; l
		db  65h	; e
		db  20h
		db  62h	; b
		db  65h	; e
		db  66h	; f
		db  6Fh	; o
		db  72h	; r
		db  65h	; e
		db  20h
		db  64h	; d
		db  6Fh	; o
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  20h
		db  61h	; a
		db  6Eh	; n
		db  79h	; y
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  63h	; c
		db  6Fh	; o
		db  2Dh	; -
		db  70h	; p
		db  72h	; r
		db  6Fh	; o
		db  63h	; c
		db  65h	; e
		db  73h	; s
		db  73h	; s
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  20h
		db  4Fh	; O
		db  52h	; R
		db  20h
		db  79h	; y
		db  6Fh	; o
		db  75h	; u
		db  20h
		db  6Dh	; m
		db  61h	; a
		db  79h	; y
		db  20h
		db  4Ch	; L
		db  4Fh	; O
		db  53h	; S
		db  45h	; E
		db  20h
		db  44h	; D
		db  49h	; I
		db  53h	; S
		db  4Bh	; K
		db  20h
		db  44h	; D
		db  41h	; A
		db  54h	; T
		db  41h	; A
		db  2Eh	; .
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  20h
		db  0Ah
		db  0Dh
		db  24h	; $
		db    0
		db    0
byte_C06	db 0			; DATA XREF: sub_1854+9w
		db    0
byte_C08	db 0			; DATA XREF: start+C1Ew
str_c09		db  43h	; C
		db  4Fh	; O
		db  4Dh	; M
		db  50h	; P
		db  41h	; A
		db  51h	; Q
		db    0
		db    0
word_C11	dw 0			; DATA XREF: start:loc_1300w
					; sub_3852+1r
word_C13	dw 0			; DATA XREF: start+11E5w start+11E9r ...
word_C15	dw 0			; DATA XREF: start:loc_1323w
					; start+122Fr ...
byte_C17	db 0			; DATA XREF: start+1240w
word_C18	dw 0			; DATA XREF: start+1236w
word_C1A	dw 0			; DATA XREF: start+1316w
word_C1C	dw 0			; DATA XREF: start+131Dw
byte_C1E	db 0			; DATA XREF: start+F5Fw sub_16F9+1r
str_0C1Fh		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
byte_CA7	db 20h			; DATA XREF: start+F49w start+F54w ...
byte_CA8	db 0			; DATA XREF: start+1394w
					; start:loc_14FFr
byte_CA9	db 0			; DATA XREF: start+FB7w start+1364r
byte_CAA	db 80h			; DATA XREF: start+1357w
byte_CAB	db 0			; DATA XREF: start+CDCw start+CF6w ...
byte_CAC	db 0			; DATA XREF: start+D43w start:loc_F0Br ...
; ���������������������������������������������������������������������������

loc_CAD:				; CODE XREF: start+2j
		mov	ax, cs
		mov	ds, ax
		mov	es, ax

		nop
		nop
		nop
		nop
		nop


		mov	ax, cs
		cli
		mov	ss, ax
		mov	sp, 3A2h
		sti
		cld
		mov	si, str_107  

		call	sub_1789 ; print PCTurbo 286e System Version 1.26
		mov	si, str_18a0
		call	sub_1789 ; print 06/05/87
		mov	si, str_12a
		call	sub_1789 ; print (C) Copyright 1986 More Computing. All Rights Reserved.
		push	es
		mov	si, str_80Bh
		mov	ax, 0F000h
		mov	es, ax

		mov	di, 0E00Ah
		mov	cx, 0Bh
		repe cmpsb		; check location 0xE00A for the string PCTurbo 286
		pop	es			; to see if they PCTurbo is already running

		jnz	short loc_CEB 	; PCTurbo not running
		mov	si, str_6D2
		call	sub_1789 ; print Already executing on the PCturbo 286!
		int	20h		; DOS -	PROGRAM	TERMINATION
					; returns to DOS--identical to INT 21/AH=00h
; ���������������������������������������������������������������������������

loc_CEB:				; CODE XREF: start+BE1j
		mov	ax, 0
		mov	es, ax

		les	di, es:38h

		sub	di, 0Ch
		mov	si, str_2403
		mov	cx, 6
		cld
		repe cmpsw			; compare es:38h with PCturb
		jnz	short loc_D0B
		mov	si, str_71b
		call	sub_1789	; Turbo already loaded. (/! option used. Use Alt grey+ to swap)
		int	20h		; DOS -	PROGRAM	TERMINATION
					; returns to DOS--identical to INT 21/AH=00h
; ���������������������������������������������������������������������������

loc_D0B:				; CODE XREF: start+C01j
		mov	ax, 0F000h
		mov	es, ax

		mov	di, 0FFEAh
		mov	si, str_c09
		mov	cx, 6
		cld
		repe cmpsb			; Compare 0FFEAh with word COMPAQ
		jnz	short loc_D28
		mov	byte [byte_C08], 1  
		mov	byte [byte_172], 1

loc_D28:				; CODE XREF: start+C1Cj
		mov	si, 80h		
		lodsb
		cmp	al, 0		; check if there are any parameters
		jnz	short loc_D33

loc_D30:				; CODE XREF: start+C44j
						; no command line parameters
		jmp	loc_ECF	
		
; ���������������������������������������������������������������������������

loc_D33:

		mov	si, str_5D7h
		call	sub_1789	; print Internal format error 286 bios code missing
		int	20h		; DOS -	PROGRAM	TERMINATION
					; returns to DOS--identical to INT 21/AH=00h

; ���������������������������������������������������������������������������


; ���������������������������������������������������������������������������
; START	OF FUNCTION CHUNK FOR start

loc_ECF:				; CODE XREF: start:loc_D30j start+D83j
		mov	dx, str_607h
		mov	ax, 3D00h
		int	21h		; DOS -	2+ - OPEN DISK FILE WITH HANDLE
					; DS:DX	-> ASCIZ filename
					; AL = access mode
					; 0 - read
		jb	short loc_EF8	; Detect for presence of EMM (EMMXXXX0), if not present jump to EF8h
		mov	ah, 41h
		int	67h		;  - LIM EMS - GET PAGE	FRAME SEGMENT
					; Return: AH = 00h function successful,	BX = segment of	page frame
					; AH = error code
		cmp	ah, 0
		jnz	short loc_EF8  
		and	bx, 0F000h
		mov	ax, [word_182]
		and	ax, 0F000h
		cmp	bx, ax
		jnz	short loc_EF8	; Turbo.com and EMM don't share same memory segment
		mov	si, str_610h
		call	sub_1789  ; print STARTUP ERROR - Extended Memory (EMM) driver installed at same memory segment address as TURBO.COM
					      ;	Please RE-INSTALL your PCturbo 286e system software.
		int	20h		; DOS -	PROGRAM	TERMINATION
					; returns to DOS--identical to INT 21/AH=00h
; ���������������������������������������������������������������������������


loc_EF8:				; CODE XREF: start+DD7j start+DE0j ...
		cmp	byte [byte_16C], 0
		jz	short loc_F0B
		mov	si, str_3F9h   ; print new line
		call	sub_1789
		mov	si, str_0A33h  ; print The /S option of the turbo command is not currently supported.
		call	sub_1789

loc_F0B:				; CODE XREF: start+DFDj
		cmp	byte [byte_CAC], 1
		jnz	short loc_F1E
		mov	si, str_3F9h  ; print new line
		call	sub_1789
		mov	si, str_0A74h ; print Coprocessing Version of PCturbo 286e System
		call	sub_1789

loc_F1E:				; CODE XREF: start+E10j
		cmp	byte [byte_185], 1
		jz	short loc_F28

		jmp	loc_102E

loc_F28:	
		mov	si, str_9EBh;
		call	sub_1789	; Turbo already loaded. (/! option used. Use Alt grey+ to swap)
		int	20h		; DOS -	PROGRAM	TERMINATION
					; returns to DOS--identical to INT 21/AH=00h						


; ���������������������������������������������������������������������������


loc_102E:				; CODE XREF: start+E25j
		cmp	byte [byte_175], 1
		jnz	short loc_103F
		mov	byte [byte_2123], 89h
		mov	byte [byte_212F], 89h

loc_103F:				; CODE XREF: start+F33j
		mov	ax, [word_182]
		mov	cl, 4
		shr	ah, cl
		sub	ah, 8
		or	byte [byte_CA7], ah
		cmp	byte [byte_16F], 0
		jz	short loc_1059
		or	byte [byte_CA7], 10h

loc_1059:				; CODE XREF: start+F52j
		call	sub_160E
		cli
		in	al, 21h		; Interrupt controller,	8259A.
		mov	byte [byte_C1E], al
		push	ds
		mov	si, 0
		mov	ds, si
		mov	di, str_0C1Fh
		push	cs
		pop	es

		mov	cx, 88h
		rep movsb
		pop	ds
		sti
		cmp	byte [byte_CAB], 1
		jz	short loc_10C4
		call	sub_1828
		mov	al, 0Fh
		call	sub_1854
		mov	es, [word_182]

		mov	si, str_80Bh  ; PCturbo 286
		mov	di, 0E00Ah
		mov	cx, 0Bh
		repe cmpsb
		jnz	short loc_10C4
		mov	cx, 64h
		mov	byte  es:0FFFDh, 0A5h

loc_109D:				; CODE XREF: start+FA3j
		cmp	byte es:0FFFDh, 5Ah
		loopne	loc_109D
		jnz	short loc_10C4
		mov	byte es:0FFFDh, 0F0h

loc_10AD:				; CODE XREF: start+FB3j
		cmp	byte es:0FFFDh, 0Fh
		loopne	loc_10AD
		jnz	short loc_10C4
		mov	byte [byte_CA9], 1
		or	byte [byte_CA7], 80h
		jmp	loc_12D9
; ���������������������������������������������������������������������������


loc_10C4:				; CODE XREF: start+F79j start+F92j ...
		call	sub_183B
		mov	dx, [word_178]
		add	dl, 7
		out	dx, al
		mov	dx, [word_178]
		add	dl, 6
		in	al, dx
		mov	dx, [word_178]
		add	dl, 0
		in	al, dx
		mov	dx, [word_178]
		add	dl, 1
		mov	al, 0
		out	dx, al
		call	sub_1828
		mov	al, 0Fh
		call	sub_1854
		mov	es, [word_182]
		mov	word es:0, 5AA5h
		mov	word es:2, 0A55Ah
		cmp	word es:0, 5AA5h
		jnz	short loc_1118
		cmp	word es:2, 0A55Ah
		jnz	short loc_1118
		jmp	short loc_1120
; END OF FUNCTION CHUNK	FOR start
; ���������������������������������������������������������������������������
		db  90h	; �
; ���������������������������������������������������������������������������
; START	OF FUNCTION CHUNK FOR start

loc_1118:				; CODE XREF: start+100Aj start+1013j
		mov	si, str_3A3h  
		call	sub_1789  ; print Cannot access the PCturbo 286e Card. Please check all board jumpers and try again.
		int	20h		; DOS -	PROGRAM	TERMINATION
					; returns to DOS--identical to INT 21/AH=00h
; ���������������������������������������������������������������������������

loc_1120:
		mov	si, str_9D0h;
		call	sub_1789	; Turbo already loaded. (/! option used. Use Alt grey+ to swap)
		int	20h		; DOS -	PROGRAM	TERMINATION
					; returns to DOS--identical to INT 21/AH=00h						



loc_12D9:

		mov	si, str_0A74h;
		call	sub_1789	; Turbo already loaded. (/! option used. Use Alt grey+ to swap)
		int	20h		; DOS -	PROGRAM	TERMINATION
					; returns to DOS--identical to INT 21/AH=00h						


; ���������������������������������������������������������������������������
str_15E2h		db  4Fh	; O
		db  52h	; R
		db  43h	; C
		db  48h	; H
		db  49h	; I
		db  44h	; D
		db  20h
		db  43h	; C
		db  47h	; G
		db  41h	; A
		db  20h
		db  45h	; E
		db  4Dh	; M
		db  55h	; U
		db  4Ch	; L
str_15F1h		db  4Fh	; O
		db  52h	; R
		db  43h	; C
		db  48h	; H
		db  49h	; I
		db  44h	; D
		db  20h
		db  48h	; H
		db  47h	; G
		db  43h	; C
		db  20h
		db  46h	; F
		db  55h	; U
		db  4Ch	; L
		db  4Ch	; L

word_1600	dw 0			; DATA XREF: sub_160Ew	sub_160E+Bw ...
word_1602	dw 103h			; DATA XREF: sub_1670r
word_1604	dw 112h			; DATA XREF: sub_1659+11w sub_167Br
word_1606	dw 0			; DATA XREF: sub_16A3+9w sub_16C8+5r
word_1608	dw 0			; DATA XREF: sub_16A3+Fw sub_16C8+Cr
word_160A	dw 0			; DATA XREF: sub_16A3+1Aw sub_16C8+13r
word_160C	dw 0			; DATA XREF: sub_16A3+20w sub_16C8+1Ar


; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_160E:;	proc near		; CODE XREF: start:loc_1059p
		mov	word [word_1600], 0
		call	sub_1637
		jnb	short locret_1628
		mov	word [word_1600], 1
		call	sub_16EB
		call	sub_16A3
		call	sub_167B

locret_1628:				; CODE XREF: sub_160E+9j
		retn
;sub_160E	endp

; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_1629:;	proc near		; CODE XREF: start+1440p
		cmp	word [word_1600], 1
		jnz	short locret_1636
		call	sub_16C8
		call	sub_16F2

locret_1636:				; CODE XREF: sub_1629+5j
		retn
;sub_1629	endp


; ��������������� S U B	R O U T	I N E ���������������������������������������



sub_1637:;	proc near		; CODE XREF: sub_160E+6p
		mov	ax, 0
		mov	es, ax

		les	di, es:8

		call	sub_1659
		jz	short loc_1657
		mov	ax, 0
		mov	es, ax

		les	di, es:40h

		call	sub_1659
		jz	short loc_1657
		clc
		retn
; ���������������������������������������������������������������������������

loc_1657:				; CODE XREF: sub_1637+Dj sub_1637+1Cj
		stc
		retn
;sub_1637	endp


; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_1659:;	proc near		; CODE XREF: sub_1637+Ap sub_1637+19p
		mov	si, str_15E2h   ; ORCHID CGA EMUL
		call	sub_1670
		jz	short locret_166F
		mov	si, str_15F1h   ; ORCHID CGA EMUL
		call	sub_1670
		jnz	short locret_166F
		pushf
		inc word [word_1604]
		popf

locret_166F:				; CODE XREF: sub_1659+6j sub_1659+Ej
		retn
;sub_1659	endp

; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_1670:;	proc near		; CODE XREF: sub_1659+3p sub_1659+Bp
		mov	di, [word_1602]
		mov	cx, 0Fh
		cld
		repe cmpsb
		retn
;sub_1670	endp




;sub_160E:

;		mov	si, str_951h;
;		call	sub_1789	; Turbo already loaded. (/! option used. Use Alt grey+ to swap)
;		int	20h		; DOS -	PROGRAM	TERMINATION
;					; returns to DOS--identical to INT 21/AH=00h						



; ��������������� S U B	R O U T	I N E ���������������������������������������

sub_167B:;	proc near		; CODE XREF: sub_160E+17p
		mov	di, [word_1604]
		push	ds
		xor	ax, ax
		mov	ds, ax
		cli
		mov	ax, es:[di]
		mov	[8], ax
		mov	ax, es:[di+2]
		mov	[0Ah],	ax
		mov	ax, es:[di+4]
		mov	[40h],	ax
		mov	ax, es:[di+6]
		mov	[42h],	ax
		sti
		pop	ds
		retn
;sub_167B	endp


; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_16A3:;	proc near		; CODE XREF: sub_160E+14p
		xor	ax, ax
		mov	es, ax

		les	bx, es:8

		mov word [word_1606], bx
		mov	bx, es
		mov	word [word_1608], bx
		mov	es, ax

		les	bx, es:40h

		mov	word [word_160A], bx
		mov	bx, es
		mov	word [word_160C], bx
		retn
;sub_16A3	endp


; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_16C8:;	proc near		; CODE XREF: sub_1629+7p
		xor	ax, ax
		mov	es, ax

		cli
		mov	ax, [word_1606]
		mov	es:8, ax
		mov	ax, [word_1608]
		mov	es:0Ah,	ax
		mov	ax, [word_160A]
		mov	es:40h,	ax
		mov	ax, [word_160C]
		mov	es:42h,	ax
		sti
		retn
;sub_16C8	endp



; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_16EB:;	proc near		; CODE XREF: sub_160E+11p
		mov	dx, 3C3h
		mov	al, 0
		out	dx, al
		retn
;sub_16EB	endp


; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_16F2:;	proc near		; CODE XREF: sub_1629+Ap
		mov	dx, 3C3h
		mov	al, 1
		out	dx, al
		retn
;sub_16F2	endp


; ��������������� S U B	R O U T	I N E ���������������������������������������



sub_16F9:;	proc near		; CODE XREF: start+1430p
		cli
		mov	al, [byte_C1E]
		out	21h, al		; Interrupt controller,	8259A.
		mov	di, 0
		mov	es, di
		mov	si, str_0C1Fh  ; 0
		push	cs
		pop	ds
		mov	cx, 88h
		cld
		rep movsb
		sti
		retn
;sub_16F9	endp





; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_1789:;	proc near		; CODE XREF: start+BC0p start+BC6p ...
		push	ax
		push	bx
		push	si
		push	bp
		mov	bx, 7

loc_1790:				; CODE XREF: sub_1789+13j
		mov	al, cs:[si]
		cmp	al, 24h
		jz	short loc_179E
		mov	ah, 0Eh
		int	10h		; - VIDEO - WRITE CHARACTER AND	ADVANCE	CURSOR (TTY WRITE)
					; AL = character, BH = display page (alpha modes)
					; BL = foreground color	(graphics modes)
		inc	si
		jmp	short loc_1790
; ���������������������������������������������������������������������������

loc_179E:				; CODE XREF: sub_1789+Cj
		pop	bp
		pop	si
		pop	bx
		pop	ax
		retn
;sub_1789	endp

; ���������������������������������������������������������������������������


; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_1828:;	proc near		; CODE XREF: start+F7Bp start+FE9p
		mov	dx, cs:word_180
		mov	al, 0FFh
		out	dx, al
		retn
;sub_1828	endp

; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_183B:;	proc near		; CODE XREF: start:loc_10C4p
		mov	dx, cs:word_180
		add	dl, 4
		mov	al, 0
		out	dx, al
		mov	dx, cs:word_180
		add	dl, 3
		mov	al, cs:byte_CA7
		out	dx, al
		retn
;sub_183B	endp

; ��������������� S U B	R O U T	I N E ���������������������������������������


sub_1854:;	proc near		; CODE XREF: start+F80p start+FEEp ...
		mov	dx, cs:word_180
		add	dl, 4
		out	dx, al
		mov	cs:byte_C06, al
		retn
;sub_1854	endp



; ���������������������������������������������������������������������������

		db    0
str_18a0 db  30h	; 0
		db  36h	; 6
		db  2Fh	; /
		db  30h	; 0
		db  35h	; 5
		db  2Fh	; /
		db  38h	; 8
		db  37h	; 7
		db  24h	; $
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  20h
		db  49h	; I
		db  6Eh	; n
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  6Eh	; n
		db  61h	; a
		db  6Ch	; l
		db  20h
		db  45h	; E
		db  72h	; r
		db  72h	; r
		db  6Fh	; o
		db  72h	; r
		db  3Ah	; :
		db  20h
		db  4Eh	; N
		db  6Fh	; o
		db  20h
		db  72h	; r
		db  65h	; e
		db  71h	; q
		db  75h	; u
		db  65h	; e
		db  73h	; s
		db  74h	; t
		db  20h
		db  62h	; b
		db  6Ch	; l
		db  6Fh	; o
		db  63h	; c
		db  6Bh	; k
		db  73h	; s
		db  20h
		db  61h	; a
		db  76h	; v
		db  61h	; a
		db  6Ch	; l
		db  69h	; i
		db  61h	; a
		db  62h	; b
		db  6Ch	; l
		db  65h	; e
		db  2Eh	; .
		db  0Ah
		db  0Dh
		db  24h	; $
		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  20h
		db  49h	; I
		db  6Eh	; n
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  6Eh	; n
		db  61h	; a
		db  6Ch	; l
		db  20h
		db  45h	; E
		db  72h	; r
		db  72h	; r
		db  6Fh	; o
		db  72h	; r
		db  3Ah	; :
		db  20h
		db  55h	; U
		db  6Eh	; n
		db  6Bh	; k
		db  6Eh	; n
		db  6Fh	; o
		db  77h	; w
		db  6Eh	; n
		db  20h
		db  63h	; c
		db  61h	; a
		db  75h	; u
		db  73h	; s
		db  65h	; e
		db  2Eh	; .
		db  0Ah
		db  0Dh
		db  24h	; $
		db    7
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  41h	; A
		db  20h
		db  48h	; H
		db  41h	; A
		db  52h	; R
		db  44h	; D
		db  57h	; W
		db  41h	; A
		db  52h	; R
		db  45h	; E
		db  20h
		db  45h	; E
		db  52h	; R
		db  52h	; R
		db  4Fh	; O
		db  52h	; R
		db  20h
		db  28h	; (
		db  50h	; P
		db  41h	; A
		db  52h	; R
		db  49h	; I
		db  54h	; T
		db  59h	; Y
		db  20h
		db  43h	; C
		db  48h	; H
		db  45h	; E
		db  43h	; C
		db  4Bh	; K
		db  29h	; )
		db  20h
		db  68h	; h
		db  61h	; a
		db  73h	; s
		db  20h
		db  6Fh	; o
		db  63h	; c
		db  63h	; c
		db  75h	; u
		db  72h	; r
		db  65h	; e
		db  64h	; d
		db  20h
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  20h
		db  42h	; B
		db  6Fh	; o
		db  61h	; a
		db  72h	; r
		db  64h	; d
		db  2Eh	; .
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  54h	; T
		db  68h	; h
		db  69h	; i
		db  73h	; s
		db  20h
		db  63h	; c
		db  6Fh	; o
		db  6Eh	; n
		db  64h	; d
		db  69h	; i
		db  74h	; t
		db  69h	; i
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  52h	; R
		db  45h	; E
		db  51h	; Q
		db  55h	; U
		db  49h	; I
		db  52h	; R
		db  45h	; E
		db  53h	; S
		db  20h
		db  74h	; t
		db  68h	; h
		db  61h	; a
		db  74h	; t
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  6Dh	; m
		db  61h	; a
		db  63h	; c
		db  68h	; h
		db  69h	; i
		db  6Eh	; n
		db  65h	; e
		db  20h
		db  62h	; b
		db  65h	; e
		db  20h
		db  52h	; R
		db  45h	; E
		db  53h	; S
		db  45h	; E
		db  54h	; T
		db  20h
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  61h	; a
		db  20h
		db  64h	; d
		db  69h	; i
		db  61h	; a
		db  67h	; g
		db  6Eh	; n
		db  6Fh	; o
		db  73h	; s
		db  74h	; t
		db  69h	; i
		db  63h	; c
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  72h	; r
		db  75h	; u
		db  6Eh	; n
		db  20h
		db  74h	; t
		db  6Fh	; o
		db  20h
		db  74h	; t
		db  72h	; r
		db  79h	; y
		db  20h
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  64h	; d
		db  65h	; e
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  6Dh	; m
		db  69h	; i
		db  6Eh	; n
		db  65h	; e
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  66h	; f
		db  61h	; a
		db  69h	; i
		db  6Ch	; l
		db  75h	; u
		db  72h	; r
		db  65h	; e
		db  20h
		db  63h	; c
		db  61h	; a
		db  75h	; u
		db  73h	; s
		db  65h	; e
		db  20h
		db  28h	; (
		db  53h	; S
		db  65h	; e
		db  65h	; e
		db  20h
		db  55h	; U
		db  73h	; s
		db  65h	; e
		db  72h	; r
		db  20h
		db  4Dh	; M
		db  61h	; a
		db  6Eh	; n
		db  75h	; u
		db  61h	; a
		db  6Ch	; l
		db  29h	; )
		db  2Eh	; .
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  54h	; T
		db  68h	; h
		db  69h	; i
		db  73h	; s
		db  20h
		db  65h	; e
		db  72h	; r
		db  72h	; r
		db  6Fh	; o
		db  72h	; r
		db  20h
		db  6Dh	; m
		db  61h	; a
		db  6Bh	; k
		db  65h	; e
		db  73h	; s
		db  20h
		db  63h	; c
		db  6Fh	; o
		db  6Eh	; n
		db  74h	; t
		db  69h	; i
		db  6Eh	; n
		db  75h	; u
		db  65h	; e
		db  64h	; d
		db  20h
		db  6Fh	; o
		db  70h	; p
		db  65h	; e
		db  72h	; r
		db  61h	; a
		db  74h	; t
		db  69h	; i
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  6Fh	; o
		db  66h	; f
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  20h
		db  55h	; U
		db  4Eh	; N
		db  52h	; R
		db  45h	; E
		db  4Ch	; L
		db  49h	; I
		db  41h	; A
		db  42h	; B
		db  4Ch	; L
		db  45h	; E
		db  2Eh	; .
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  59h	; Y
		db  6Fh	; o
		db  75h	; u
		db  20h
		db  73h	; s
		db  68h	; h
		db  6Fh	; o
		db  75h	; u
		db  6Ch	; l
		db  64h	; d
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  72h	; r
		db  65h	; e
		db  66h	; f
		db  6Fh	; o
		db  72h	; r
		db  65h	; e
		db  20h
		db  52h	; R
		db  45h	; E
		db  42h	; B
		db  4Fh	; O
		db  4Fh	; O
		db  54h	; T
		db  20h
		db  28h	; (
		db  43h	; C
		db  74h	; t
		db  6Ch	; l
		db  2Dh	; -
		db  41h	; A
		db  6Ch	; l
		db  74h	; t
		db  2Dh	; -
		db  44h	; D
		db  65h	; e
		db  6Ch	; l
		db  29h	; )
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  73h	; s
		db  79h	; y
		db  73h	; s
		db  74h	; t
		db  65h	; e
		db  6Dh	; m
		db  20h
		db  49h	; I
		db  4Dh	; M
		db  4Dh	; M
		db  45h	; E
		db  44h	; D
		db  49h	; I
		db  41h	; A
		db  54h	; T
		db  45h	; E
		db  4Ch	; L
		db  59h	; Y
		db  2Eh	; .
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  49h	; I
		db  66h	; f
		db  20h
		db  79h	; y
		db  6Fh	; o
		db  75h	; u
		db  20h
		db  68h	; h
		db  61h	; a
		db  76h	; v
		db  65h	; e
		db  20h
		db  75h	; u
		db  70h	; p
		db  2Dh	; -
		db  74h	; t
		db  6Fh	; o
		db  2Dh	; -
		db  64h	; d
		db  61h	; a
		db  74h	; t
		db  65h	; e
		db  20h
		db  42h	; B
		db  41h	; A
		db  43h	; C
		db  4Bh	; K
		db  55h	; U
		db  50h	; P
		db  53h	; S
		db  20h
		db  6Fh	; o
		db  66h	; f
		db  20h
		db  41h	; A
		db  4Ch	; L
		db  4Ch	; L
		db  20h
		db  44h	; D
		db  41h	; A
		db  54h	; T
		db  41h	; A
		db  20h
		db  4Fh	; O
		db  4Eh	; N
		db  20h
		db  54h	; T
		db  48h	; H
		db  49h	; I
		db  53h	; S
		db  20h
		db  53h	; S
		db  59h	; Y
		db  53h	; S
		db  54h	; T
		db  45h	; E
		db  4Dh	; M
		db  2Ch	; ,
		db  20h
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  77h	; w
		db  61h	; a
		db  6Eh	; n
		db  74h	; t
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  74h	; t
		db  6Fh	; o
		db  20h
		db  61h	; a
		db  74h	; t
		db  74h	; t
		db  65h	; e
		db  6Dh	; m
		db  70h	; p
		db  74h	; t
		db  20h
		db  74h	; t
		db  6Fh	; o
		db  20h
		db  73h	; s
		db  61h	; a
		db  76h	; v
		db  65h	; e
		db  20h
		db  77h	; w
		db  6Fh	; o
		db  72h	; r
		db  6Bh	; k
		db  20h
		db  69h	; i
		db  6Eh	; n
		db  20h
		db  70h	; p
		db  72h	; r
		db  6Fh	; o
		db  67h	; g
		db  72h	; r
		db  65h	; e
		db  73h	; s
		db  73h	; s
		db  20h
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Ch	; ,
		db  20h
		db  79h	; y
		db  6Fh	; o
		db  75h	; u
		db  20h
		db  6Dh	; m
		db  61h	; a
		db  79h	; y
		db  20h
		db  61h	; a
		db  74h	; t
		db  74h	; t
		db  65h	; e
		db  6Dh	; m
		db  70h	; p
		db  74h	; t
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  74h	; t
		db  6Fh	; o
		db  20h
		db  63h	; c
		db  6Fh	; o
		db  6Eh	; n
		db  74h	; t
		db  69h	; i
		db  6Eh	; n
		db  75h	; u
		db  65h	; e
		db  20h
		db  62h	; b
		db  79h	; y
		db  20h
		db  70h	; p
		db  72h	; r
		db  65h	; e
		db  73h	; s
		db  73h	; s
		db  69h	; i
		db  6Eh	; n
		db  67h	; g
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  46h	; F
		db  31h	; 1
		db  20h
		db  6Bh	; k
		db  65h	; e
		db  79h	; y
		db  2Eh	; .
		db  20h
		db  53h	; S
		db  41h	; A
		db  56h	; V
		db  45h	; E
		db  20h
		db  79h	; y
		db  6Fh	; o
		db  75h	; u
		db  72h	; r
		db  20h
		db  57h	; W
		db  4Fh	; O
		db  52h	; R
		db  4Bh	; K
		db  20h
		db  49h	; I
		db  4Dh	; M
		db  4Dh	; M
		db  45h	; E
		db  44h	; D
		db  49h	; I
		db  41h	; A
		db  54h	; T
		db  45h	; E
		db  4Ch	; L
		db  59h	; Y
		db  20h
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  61h	; a
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  53h	; S
		db  43h	; C
		db  52h	; R
		db  41h	; A
		db  54h	; T
		db  43h	; C
		db  48h	; H
		db  20h
		db  46h	; F
		db  4Ch	; L
		db  4Fh	; O
		db  50h	; P
		db  50h	; P
		db  59h	; Y
		db  20h
		db  4Fh	; O
		db  4Eh	; N
		db  4Ch	; L
		db  59h	; Y
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  6Eh	; n
		db  20h
		db  52h	; R
		db  45h	; E
		db  42h	; B
		db  4Fh	; O
		db  4Fh	; O
		db  54h	; T
		db  20h
		db  41h	; A
		db  53h	; S
		db  20h
		db  53h	; S
		db  4Fh	; O
		db  4Fh	; O
		db  4Eh	; N
		db  20h
		db  41h	; A
		db  53h	; S
		db  20h
		db  50h	; P
		db  4Fh	; O
		db  53h	; S
		db  53h	; S
		db  49h	; I
		db  42h	; B
		db  4Ch	; L
		db  45h	; E
		db  20h
		db  21h	; !
		db  21h	; !
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  43h	; C
		db  6Fh	; o
		db  6Eh	; n
		db  74h	; t
		db  69h	; i
		db  6Eh	; n
		db  75h	; u
		db  65h	; e
		db  64h	; d
		db  20h
		db  6Fh	; o
		db  70h	; p
		db  65h	; e
		db  72h	; r
		db  61h	; a
		db  74h	; t
		db  69h	; i
		db  6Fh	; o
		db  6Eh	; n
		db  20h
		db  69h	; i
		db  73h	; s
		db  20h
		db  55h	; U
		db  4Eh	; N
		db  52h	; R
		db  45h	; E
		db  4Ch	; L
		db  49h	; I
		db  41h	; A
		db  42h	; B
		db  4Ch	; L
		db  45h	; E
		db  20h
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  73h	; s
		db  68h	; h
		db  6Fh	; o
		db  75h	; u
		db  6Ch	; l
		db  64h	; d
		db  20h
		db  62h	; b
		db  65h	; e
		db  20h
		db  61h	; a
		db  74h	; t
		db  74h	; t
		db  65h	; e
		db  6Dh	; m
		db  70h	; p
		db  65h	; e
		db  64h	; d
		db  20h
		db  4Fh	; O
		db  4Eh	; N
		db  4Ch	; L
		db  59h	; Y
		db  20h
		db  77h	; w
		db  69h	; i
		db  74h	; t
		db  68h	; h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  20h
		db  70h	; p
		db  72h	; r
		db  6Fh	; o
		db  70h	; p
		db  65h	; e
		db  72h	; r
		db  20h
		db  62h	; b
		db  61h	; a
		db  63h	; c
		db  6Bh	; k
		db  75h	; u
		db  70h	; p
		db  20h
		db  61h	; a
		db  6Eh	; n
		db  64h	; d
		db  20h
		db  69h	; i
		db  66h	; f
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  77h	; w
		db  6Fh	; o
		db  72h	; r
		db  6Bh	; k
		db  20h
		db  69h	; i
		db  6Eh	; n
		db  20h
		db  70h	; p
		db  72h	; r
		db  6Fh	; o
		db  67h	; g
		db  72h	; r
		db  65h	; e
		db  73h	; s
		db  73h	; s
		db  20h
		db  69h	; i
		db  73h	; s
		db  20h
		db  69h	; i
		db  72h	; r
		db  72h	; r
		db  65h	; e
		db  70h	; p
		db  72h	; r
		db  6Fh	; o
		db  64h	; d
		db  75h	; u
		db  63h	; c
		db  69h	; i
		db  62h	; b
		db  6Ch	; l
		db  65h	; e
		db  2Eh	; .
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  0Ah
		db  0Dh
		db    7
		db  24h	; $
		db    7
		db  50h	; P
		db  43h	; C
		db  4Dh	; M
		db  41h	; A
		db  49h	; I
		db  4Eh	; N
		db  3Ah	; :
		db  20h
		db  49h	; I
		db  6Eh	; n
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  66h	; f
		db  61h	; a
		db  63h	; c
		db  65h	; e
		db  20h
		db  45h	; E
		db  72h	; r
		db  72h	; r
		db  6Fh	; o
		db  72h	; r
		db  20h
		db  2Dh	; -
		db  20h
		db  55h	; U
		db  6Eh	; n
		db  6Bh	; k
		db  6Eh	; n
		db  6Fh	; o
		db  77h	; w
		db  6Eh	; n
		db  20h
		db  50h	; P
		db  49h	; I
		db  44h	; D
		db  20h
		db  24h	; $
		db    0
		db 0FFh
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0

byte_2123	db 9			; DATA XREF: start+F35w
		db  2Eh	; .
		db  8Bh	; �
		db  16h
		db  7Ch	; |
		db    1
		db 0EEh	; �
		db  2Eh	; .
		db 0A0h	; �
		db  23h	; #
		db  21h	; !
		db  34h	; 4
byte_212F	db 9			; DATA XREF: start+F3Aw
		db  2Eh	; .
		db 0A2h	; �
		db  23h	; #
		db  21h	; !
		db  5Ah	; Z
		db  5Bh	; [
		db  58h	; X
		db 0CFh	; �
		db 0E9h	; �
		db 0B7h	; �
		db 0FEh	; �
		db 0F6h	; �
		db 0C4h	; �
		db    4



str_2403		db  50h	; P
		db  43h	; C
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  62h	; b
		db  6Fh	; o
		db  2Dh	; -
		db  32h	; 2
		db  38h	; 8
		db  36h	; 6
		db  65h	; e




;seg000		ends


;		end start
